// <auto-generated />
namespace Schools.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DirectorAddedToSchool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DirectorAddedToSchool));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111557363_DirectorAddedToSchool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
